# Generated by Django 4.2.16 on 2025-11-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_alter_document_effective_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="effective_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
