# Generated by Django 4.2.7 on 2025-11-21 07:27

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('change_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('RESET', 'Reset to Default')], max_length=20)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuration History',
                'verbose_name_plural': 'Configuration History',
                'db_table': 'configuration_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.CharField(help_text='Unique feature toggle key', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('toggle_type', models.CharField(choices=[('RELEASE', 'Release Toggle'), ('EXPERIMENT', 'Experiment Toggle'), ('OPERATIONAL', 'Operational Toggle'), ('PERMISSION', 'Permission Toggle')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether the feature is currently enabled')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditions for enabling this feature')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='Roles that have access to this feature')),
                ('rollout_percentage', models.PositiveIntegerField(default=0, help_text='Percentage of users to enable feature for (0-100)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField(blank=True, help_text='When to start enabling this feature', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop enabling this feature', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Toggle',
                'verbose_name_plural': 'Feature Toggles',
                'db_table': 'feature_toggles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('EMAIL', 'Email Template'), ('SMS', 'SMS Template'), ('DASHBOARD', 'Dashboard Notification'), ('PUSH', 'Push Notification')], max_length=20)),
                ('event_type', models.CharField(choices=[('DOCUMENT_APPROVED', 'Document Approved'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('WORKFLOW_ASSIGNED', 'Workflow Task Assigned'), ('WORKFLOW_OVERDUE', 'Workflow Task Overdue'), ('DOCUMENT_EFFECTIVE', 'Document Became Effective'), ('DOCUMENT_OBSOLETE', 'Document Became Obsolete'), ('SYSTEM_ALERT', 'System Alert'), ('BACKUP_COMPLETED', 'Backup Completed'), ('BACKUP_FAILED', 'Backup Failed'), ('USER_ACCOUNT_CREATED', 'User Account Created'), ('PASSWORD_RESET', 'Password Reset')], max_length=30)),
                ('subject_template', models.CharField(blank=True, help_text='Subject line template (for email/SMS)', max_length=200)),
                ('body_template', models.TextField(help_text='Message body template')),
                ('html_template', models.TextField(blank=True, help_text='HTML template (for email)')),
                ('available_variables', models.JSONField(default=list, help_text='List of available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_templates',
                'ordering': ['template_type', 'event_type'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.CharField(help_text='Unique configuration key', max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SYSTEM', 'System Settings'), ('SECURITY', 'Security Settings'), ('APPEARANCE', 'Appearance Settings'), ('NOTIFICATION', 'Notification Settings'), ('INTEGRATION', 'Integration Settings'), ('WORKFLOW', 'Workflow Settings'), ('BACKUP', 'Backup Settings'), ('AUDIT', 'Audit Settings'), ('DOCUMENT', 'Document Settings')], max_length=20)),
                ('setting_type', models.CharField(choices=[('STRING', 'String Value'), ('INTEGER', 'Integer Value'), ('FLOAT', 'Float Value'), ('BOOLEAN', 'Boolean Value'), ('JSON', 'JSON Object'), ('FILE_PATH', 'File Path'), ('URL', 'URL'), ('EMAIL', 'Email Address'), ('COLOR', 'Color Code')], max_length=20)),
                ('value', models.TextField(blank=True, help_text='Current setting value')),
                ('default_value', models.TextField(blank=True, help_text='Default setting value')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules for the setting value')),
                ('allowed_values', models.JSONField(blank=True, default=list, help_text='List of allowed values (for choice fields)')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this setting contains sensitive information')),
                ('requires_restart', models.BooleanField(default=False, help_text='Whether changing this setting requires application restart')),
                ('is_user_configurable', models.BooleanField(default=True, help_text='Whether users can modify this setting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'system_configurations',
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='UICustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('customization_type', models.CharField(choices=[('LOGO', 'Company Logo'), ('BANNER', 'Page Banner'), ('THEME', 'Color Theme'), ('FONT', 'Font Settings'), ('LAYOUT', 'Layout Configuration'), ('DASHBOARD', 'Dashboard Settings'), ('MENU', 'Menu Configuration')], max_length=20)),
                ('settings_data', models.JSONField(default=dict, help_text='Customization settings and values')),
                ('uploaded_file', models.FileField(blank=True, help_text='Uploaded file for this customization', null=True, upload_to='customizations/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default customization')),
                ('target_departments', models.JSONField(blank=True, default=list, help_text='Departments this customization applies to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UI Customization',
                'verbose_name_plural': 'UI Customizations',
                'db_table': 'ui_customizations',
                'ordering': ['customization_type', 'name'],
            },
        ),
    ]
