# Generated by Django 4.2.16 on 2025-11-23 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflows", "0002_documentstate_documentworkflow_documenttransition"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentworkflow",
            name="effective_date",
            field=models.DateField(
                blank=True,
                help_text="Date when approved document becomes effective",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentworkflow",
            name="is_terminated",
            field=models.BooleanField(
                default=False,
                help_text="Whether workflow has been terminated by author",
            ),
        ),
        migrations.AddField(
            model_name="documentworkflow",
            name="last_approved_state",
            field=models.CharField(
                blank=True,
                help_text="Last approved state before termination",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="documentworkflow",
            name="obsoleting_date",
            field=models.DateField(
                blank=True, help_text="Date when document becomes obsolete", null=True
            ),
        ),
        migrations.AddField(
            model_name="documentworkflow",
            name="obsoleting_reason",
            field=models.TextField(
                blank=True, help_text="Reason for obsoleting document"
            ),
        ),
        migrations.AddField(
            model_name="documentworkflow",
            name="selected_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="selected_approver_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentworkflow",
            name="selected_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="selected_reviewer_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentworkflow",
            name="termination_reason",
            field=models.TextField(
                blank=True, help_text="Reason for terminating workflow"
            ),
        ),
        migrations.AddField(
            model_name="documentworkflow",
            name="up_version_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for up-versioning (required for up-version workflow)",
            ),
        ),
        migrations.AddField(
            model_name="documentworkflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("REVIEW", "Review Workflow"),
                    ("UP_VERSION", "Up-versioning Workflow"),
                    ("OBSOLETE", "Obsolete Workflow"),
                    ("TERMINATION", "Termination Workflow"),
                ],
                default="REVIEW",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentstate",
            name="code",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("REVIEWED", "Reviewed"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED_PENDING_EFFECTIVE", "Approved, Pending Effective"),
                    ("APPROVED_AND_EFFECTIVE", "Approved and Effective"),
                    ("SUPERSEDED", "Superseded"),
                    ("PENDING_OBSOLETION", "Pending Obsoletion"),
                    ("OBSOLETE", "Obsolete"),
                ],
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
