"""
PDF Report Generator for Compliance Reports
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.platypus import Image as RLImage
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
import json


def generate_compliance_pdf(report, metrics, output_path):
    """
    Generate a professional PDF compliance report
    
    Args:
        report: ComplianceReport instance
        metrics: Dictionary containing report metrics
        output_path: Path where PDF should be saved
    """
    
    # Create the PDF document
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=18,
    )
    
    # Container for the 'Flowable' objects
    elements = []
    
    # Define styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1a56db'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#1a56db'),
        spaceAfter=12,
        spaceBefore=12
    )
    
    subheading_style = ParagraphStyle(
        'CustomSubHeading',
        parent=styles['Heading3'],
        fontSize=12,
        textColor=colors.HexColor('#374151'),
        spaceAfter=6,
    )
    
    normal_style = styles['Normal']
    
    # Add title
    title = Paragraph(report.name, title_style)
    elements.append(title)
    elements.append(Spacer(1, 0.2*inch))
    
    # Add report metadata
    metadata_data = [
        ['Report Type:', report.get_report_type_display()],
        ['Generated By:', report.generated_by.get_full_name() or report.generated_by.username],
        ['Generated At:', report.generated_at.strftime('%Y-%m-%d %H:%M:%S %Z')],
        ['Report Period:', f"{metrics['report_period']['start'][:10]} to {metrics['report_period']['end'][:10]}"],
    ]
    
    if report.description:
        metadata_data.append(['Description:', report.description])
    
    metadata_table = Table(metadata_data, colWidths=[2*inch, 4*inch])
    metadata_table.setStyle(TableStyle([
        ('FONT', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONT', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#374151')),
        ('TEXTCOLOR', (1, 0), (1, -1), colors.black),
        ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
    ]))
    
    elements.append(metadata_table)
    elements.append(Spacer(1, 0.3*inch))
    
    # Add executive summary
    elements.append(Paragraph('Executive Summary', heading_style))
    elements.append(Spacer(1, 0.1*inch))
    
    # Add summary statistics
    if report.summary_stats:
        summary_data = [['Metric', 'Value']]
        for key, value in report.summary_stats.items():
            label = key.replace('_', ' ').title()
            summary_data.append([label, str(value)])
        
        summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
        summary_table.setStyle(TableStyle([
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONT', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a56db')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')]),
        ]))
        
        elements.append(summary_table)
        elements.append(Spacer(1, 0.3*inch))
    
    # Add detailed metrics sections
    _add_metrics_sections(elements, metrics, heading_style, subheading_style, normal_style)
    
    # Add footer with report integrity information
    elements.append(PageBreak())
    elements.append(Paragraph('Report Integrity', heading_style))
    elements.append(Spacer(1, 0.1*inch))
    
    integrity_text = f"""
    This report was generated automatically by the EDMS Compliance System.
    <br/>
    <b>Report UUID:</b> {report.uuid}
    <br/>
    <b>Generation Time:</b> {report.generated_at.strftime('%Y-%m-%d %H:%M:%S %Z')}
    <br/>
    <b>Generated By:</b> {report.generated_by.get_full_name() or report.generated_by.username}
    <br/>
    <br/>
    This report contains confidential information and should be handled according to your organization's data security policies.
    """
    
    elements.append(Paragraph(integrity_text, normal_style))
    
    # Build the PDF
    doc.build(elements)


def _add_metrics_sections(elements, metrics, heading_style, subheading_style, normal_style):
    """Add detailed metrics sections to the PDF"""
    
    # Audit Statistics
    if 'audit_statistics' in metrics:
        elements.append(Paragraph('Audit Trail Statistics', heading_style))
        elements.append(Spacer(1, 0.1*inch))
        
        audit_data = [['Metric', 'Count']]
        for key, value in metrics['audit_statistics'].items():
            label = key.replace('_', ' ').title()
            audit_data.append([label, str(value)])
        
        audit_table = Table(audit_data, colWidths=[3.5*inch, 1.5*inch])
        audit_table.setStyle(TableStyle([
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONT', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a56db')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')]),
        ]))
        
        elements.append(audit_table)
        elements.append(Spacer(1, 0.2*inch))
    
    # Authentication Statistics
    if 'authentication' in metrics:
        elements.append(Paragraph('Authentication Activity', heading_style))
        elements.append(Spacer(1, 0.1*inch))
        
        auth_data = [['Metric', 'Count']]
        for key, value in metrics['authentication'].items():
            label = key.replace('_', ' ').title()
            auth_data.append([label, str(value)])
        
        auth_table = Table(auth_data, colWidths=[3.5*inch, 1.5*inch])
        auth_table.setStyle(TableStyle([
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONT', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a56db')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')]),
        ]))
        
        elements.append(auth_table)
        elements.append(Spacer(1, 0.2*inch))
    
    # Document Activities
    if 'document_activities' in metrics:
        elements.append(Paragraph('Document Management Activities', heading_style))
        elements.append(Spacer(1, 0.1*inch))
        
        doc_data = [['Activity Type', 'Count']]
        for key, value in metrics['document_activities'].items():
            label = key.replace('_', ' ').title()
            doc_data.append([label, str(value)])
        
        doc_table = Table(doc_data, colWidths=[3.5*inch, 1.5*inch])
        doc_table.setStyle(TableStyle([
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONT', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a56db')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')]),
        ]))
        
        elements.append(doc_table)
        elements.append(Spacer(1, 0.2*inch))
    
    # User Statistics
    if 'user_statistics' in metrics:
        elements.append(Paragraph('User Activity Statistics', heading_style))
        elements.append(Spacer(1, 0.1*inch))
        
        user_data = [['Metric', 'Value']]
        for key, value in metrics['user_statistics'].items():
            if key != 'top_users':  # Skip top_users for now
                label = key.replace('_', ' ').title()
                user_data.append([label, str(value)])
        
        user_table = Table(user_data, colWidths=[3.5*inch, 1.5*inch])
        user_table.setStyle(TableStyle([
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONT', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a56db')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')]),
        ]))
        
        elements.append(user_table)
        elements.append(Spacer(1, 0.2*inch))
    
    # Compliance Score (if present)
    if 'compliance_score' in metrics:
        elements.append(Paragraph('Compliance Assessment', heading_style))
        elements.append(Spacer(1, 0.1*inch))
        
        score = metrics['compliance_score']
        score_text = f"<b>Overall Compliance Score:</b> {score}/100"
        
        if score >= 90:
            score_text += " - Excellent"
            score_color = colors.green
        elif score >= 75:
            score_text += " - Good"
            score_color = colors.HexColor('#fbbf24')
        elif score >= 60:
            score_text += " - Acceptable"
            score_color = colors.orange
        else:
            score_text += " - Needs Improvement"
            score_color = colors.red
        
        score_para = Paragraph(score_text, normal_style)
        elements.append(score_para)
        elements.append(Spacer(1, 0.2*inch))
