# Generated by Django 4.2.7 on 2025-11-21 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placeholders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholderdefinition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_placeholders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placeholdercache',
            name='placeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='placeholders.placeholderdefinition'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='placeholders',
            field=models.ManyToManyField(related_name='templates', through='placeholders.TemplatePlaceholder', to='placeholders.placeholderdefinition'),
        ),
        migrations.AddField(
            model_name='documentgeneration',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_generations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentgeneration',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentgeneration',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='placeholders.documenttemplate'),
        ),
        migrations.AddConstraint(
            model_name='templateplaceholder',
            constraint=models.UniqueConstraint(fields=('template', 'placeholder'), name='unique_template_placeholder'),
        ),
        migrations.AddIndex(
            model_name='placeholderdefinition',
            index=models.Index(fields=['placeholder_type'], name='placeholder_placeho_893e80_idx'),
        ),
        migrations.AddIndex(
            model_name='placeholderdefinition',
            index=models.Index(fields=['data_source'], name='placeholder_data_so_0ffcf2_idx'),
        ),
        migrations.AddIndex(
            model_name='placeholderdefinition',
            index=models.Index(fields=['is_active'], name='placeholder_is_acti_8fc159_idx'),
        ),
        migrations.AddIndex(
            model_name='placeholdercache',
            index=models.Index(fields=['expires_at'], name='placeholder_expires_f0fb75_idx'),
        ),
        migrations.AddIndex(
            model_name='placeholdercache',
            index=models.Index(fields=['placeholder', 'cache_key'], name='placeholder_placeho_f08db8_idx'),
        ),
        migrations.AddConstraint(
            model_name='placeholdercache',
            constraint=models.UniqueConstraint(fields=('placeholder', 'cache_key'), name='unique_placeholder_cache_key'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['template_type'], name='document_te_templat_f8e9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['status'], name='document_te_status_9016e3_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['is_default'], name='document_te_is_defa_0dc733_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_template_version'),
        ),
        migrations.AddIndex(
            model_name='documentgeneration',
            index=models.Index(fields=['status'], name='document_ge_status_b8dcef_idx'),
        ),
        migrations.AddIndex(
            model_name='documentgeneration',
            index=models.Index(fields=['template'], name='document_ge_templat_d3a859_idx'),
        ),
        migrations.AddIndex(
            model_name='documentgeneration',
            index=models.Index(fields=['requested_by'], name='document_ge_request_055053_idx'),
        ),
        migrations.AddIndex(
            model_name='documentgeneration',
            index=models.Index(fields=['created_at'], name='document_ge_created_f238d3_idx'),
        ),
    ]
