# Generated by Django 4.2.16 on 2026-01-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0004_create_document_review_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreview',
            name='outcome',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('CONFIRMED', 'Confirmed - No changes needed'),
                    ('UPVERSION_REQUIRED', 'Up-Version Required'),
                ],
                help_text='Result of the periodic review'
            ),
        ),
    ]
