# Generated by Django 4.2.16 on 2026-01-11 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0010_add_read_at_to_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkflowTask",
        ),
    ]
