# Generated by Django 4.2.16 on 2025-12-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backup", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupconfiguration',
            name='backup_type',
            field=models.CharField(
                choices=[
                    ('FULL', 'Full Backup'), 
                    ('INCREMENTAL', 'Incremental Backup'), 
                    ('DIFFERENTIAL', 'Differential Backup'), 
                    ('DATABASE', 'Database Only'), 
                    ('FILES', 'Files Only'), 
                    ('EXPORT', 'Export Package')
                ], 
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='backup_type',
            field=models.CharField(
                choices=[
                    ('FULL', 'Full Backup'), 
                    ('INCREMENTAL', 'Incremental Backup'), 
                    ('DIFFERENTIAL', 'Differential Backup'), 
                    ('DATABASE', 'Database Only'), 
                    ('FILES', 'Files Only'), 
                    ('EXPORT', 'Export Package')
                ], 
                max_length=20
            ),
        ),
    ]
