#!/bin/bash
echo "=== Checking Backend Logs for Document Creation Error ==="
echo ""
echo "Run this on your STAGING SERVER:"
echo ""
echo "docker compose -f docker-compose.prod.yml logs backend --tail 200 | grep -A 20 -B 5 'POST.*documents'"
echo ""
echo "Or to see all recent errors:"
echo ""
echo "docker compose -f docker-compose.prod.yml logs backend --tail 100"
echo ""
echo "=== Common Issues to Look For ==="
echo "1. 'author_id' or 'author' field error - User ID not being set"
echo "2. Permission denied on /app/storage/ - File upload path issue"
echo "3. IntegrityError - Database constraint violation"
echo "4. KeyError or AttributeError - Missing field in request"
echo "5. 'User' object has no attribute - Authentication issue"
