#!/bin/bash
# Debug backend startup issues

echo "════════════════════════════════════════════════════════════════"
echo "  Backend Startup Debug"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "Please run these commands on your staging server:"
echo ""
echo "1. Check backend logs:"
echo "   docker compose -f docker-compose.prod.yml logs backend"
echo ""
echo "2. Check if backend container is even running:"
echo "   docker compose -f docker-compose.prod.yml ps backend"
echo ""
echo "3. Try to access backend shell:"
echo "   docker compose -f docker-compose.prod.yml exec backend bash"
echo ""
echo "4. Check if database is accessible FROM backend:"
echo "   docker compose -f docker-compose.prod.yml exec backend python manage.py dbshell"
echo ""
echo "5. Manually run migrations:"
echo "   docker compose -f docker-compose.prod.yml exec backend python manage.py migrate"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "Common issues that cause 'unhealthy' after 123 seconds:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. Migrations failing/stuck"
echo "   - Look for 'relation does not exist' errors"
echo "   - Look for 'could not connect to server' errors"
echo ""
echo "2. SECRET_KEY or EDMS_MASTER_KEY missing"
echo "   - Check .env file has both keys"
echo ""
echo "3. Database connection refused"
echo "   - Check DB_HOST, DB_NAME, DB_USER, DB_PASSWORD in .env"
echo ""
echo "4. Gunicorn not starting"
echo "   - Look for Python import errors"
echo "   - Look for 'bind: address already in use'"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "Quick fix attempts:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Try 1: Increase start_period to 120s (2 minutes)"
echo "   Edit docker-compose.prod.yml, backend healthcheck:"
echo "   start_period: 120s  # Change from 60s to 120s"
echo ""
echo "Try 2: Disable healthcheck temporarily to see if backend works"
echo "   Edit docker-compose.prod.yml, backend section:"
echo "   healthcheck:"
echo "     disable: true  # Add this line"
echo ""
echo "Try 3: Start services one by one"
echo "   docker compose up -d db redis"
echo "   sleep 10"
echo "   docker compose up backend  # Watch logs in real-time"
echo ""
