import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('admin');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('test123');
  await page.getByRole('button', { name: 'Show password' }).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await expect(page.getByText('EDMSDocument LibraryMy').nth(1)).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Document Library$/ }).nth(2)).toBeVisible();
  await expect(page.locator('div').filter({ hasText: 'Document LibraryManage,' }).nth(4)).toBeVisible();
  await expect(page.getByText('FiltersEffective')).toBeVisible();
  await expect(page.locator('.w-full > .bg-white')).toBeVisible();
  await expect(page.locator('.bg-white.rounded-lg.shadow-sm.border.border-gray-200.p-8')).toBeVisible();
  await page.getByRole('button', { name: 'Administration' }).click();
  await expect(page.getByRole('button', { name: '👥User Management' })).toBeVisible();
  await page.getByRole('button', { name: '👥User Management' }).click();
  await page.getByRole('button', { name: 'Create User' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('author02');
  await page.getByRole('textbox').first().press('Tab');
  await page.locator('input[type="email"]').fill('author02@edms.local');
  await page.locator('input[type="email"]').press('Tab');
  await page.getByRole('textbox').nth(2).fill('author02');
  await page.getByRole('textbox').nth(2).press('Tab');
  await page.getByRole('textbox').nth(3).fill('edms');
  await page.getByRole('textbox').nth(3).press('Tab');
  await page.getByRole('textbox', { name: 'Enter secure password...' }).fill('');
  await page.getByRole('button', { name: 'Show password' }).first().click();
  await page.getByRole('textbox', { name: 'Enter secure password...' }).click();
  await page.getByRole('textbox', { name: 'Enter secure password...' }).fill('P@ssword1234');
  await page.getByRole('textbox', { name: 'Enter secure password...' }).press('Tab');
  await page.getByRole('button', { name: 'Show password' }).click();
  await page.getByRole('textbox', { name: 'Confirm password...' }).click();
  await page.getByRole('textbox', { name: 'Confirm password...' }).fill('P@ssword1234');
  await page.getByRole('checkbox', { name: 'Document Author (write)' }).check();
  await page.locator('form').getByRole('button', { name: 'Create User' }).click();
});
