# Generated by Django 4.2.7 on 2025-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginaudit',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
