# Generated by Django 4.2.16 on 2025-11-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0003_add_missing_documentworkflow_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentworkflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("REVIEW", "Review Workflow"),
                    ("UP_VERSION", "Up-versioning Workflow"),
                    ("OBSOLETE", "Obsolete Workflow"),
                    ("TERMINATION", "Termination Workflow"),
                ],
                default="REVIEW",
                max_length=50,
            ),
        ),
    ]
