# Generated by Django 4.2.16 on 2025-11-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0004_alter_documentworkflow_workflow_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentstate",
            name="code",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("REVIEWED", "Reviewed"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("UNDER_APPROVAL", "Under Approval"),
                    ("APPROVED_PENDING_EFFECTIVE", "Approved - Pending Effective"),
                    ("APPROVED_AND_EFFECTIVE", "Approved and Effective"),
                    ("SUPERSEDED", "Superseded"),
                    ("PENDING_OBSOLETE", "Pending Obsolete"),
                    ("OBSOLETE", "Obsolete"),
                    ("TERMINATED", "Terminated"),
                ],
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
