# Generated by Django 4.2.16 on 2025-11-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="effective_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
