# Generated by Django 4.2.16 on 2025-11-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_alter_loginaudit_failure_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginaudit",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
