# Generated by Django 4.2.7 on 2025-11-21 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataintegritycheck',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='databasechangelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditquerylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='involved_users',
            field=models.ManyToManyField(blank=True, related_name='involved_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='primary_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='related_audit_logs',
            field=models.ManyToManyField(blank=True, to='audit.audittrail'),
        ),
        migrations.AddField(
            model_name='auditconfiguration',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dataintegritycheck',
            index=models.Index(fields=['check_type', 'started_at'], name='data_integr_check_t_37b987_idx'),
        ),
        migrations.AddIndex(
            model_name='dataintegritycheck',
            index=models.Index(fields=['status', 'started_at'], name='data_integr_status_4ee6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='dataintegritycheck',
            index=models.Index(fields=['is_automated', 'started_at'], name='data_integr_is_auto_55f3db_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['report_type', 'generated_at'], name='compliance__report__9c531e_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['generated_by', 'generated_at'], name='compliance__generat_440bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['status'], name='compliance__status_dd1ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['timestamp', 'action'], name='audit_trail_timesta_2ba586_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['user', 'timestamp'], name='audit_trail_user_id_d519bc_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_trail_content_287296_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['session_id', 'timestamp'], name='audit_trail_session_a6d161_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['ip_address', 'timestamp'], name='audit_trail_ip_addr_ce6651_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['module', 'action'], name='audit_trail_module_2e8fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['checksum'], name='audit_trail_checksu_e34cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditquerylog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_query_user_id_2a7fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditquerylog',
            index=models.Index(fields=['query_type', 'timestamp'], name='audit_query_query_t_29fefc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type', 'started_at'], name='audit_event_event_t_7c067c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['primary_user', 'started_at'], name='audit_event_primary_4860cd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['is_successful', 'started_at'], name='audit_event_is_succ_3a5cb8_idx'),
        ),
    ]
