# Generated by Django 4.2.16 on 2025-11-28 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0005_expand_status_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="obsolescence_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Scheduled date for document obsolescence",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="obsolescence_reason",
            field=models.TextField(
                blank=True, help_text="Reason provided for obsolescence"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="obsoleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who initiated obsolescence",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="obsoleted_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("REVIEW_COMPLETED", "Review Completed"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("UNDER_APPROVAL", "Under Approval"),
                    ("APPROVED", "Approved"),
                    ("APPROVED_AND_EFFECTIVE", "Approved and Effective"),
                    ("APPROVED_PENDING_EFFECTIVE", "Approved Pending Effective"),
                    ("EFFECTIVE", "Effective"),
                    ("SCHEDULED_FOR_OBSOLESCENCE", "Scheduled for Obsolescence"),
                    ("SUPERSEDED", "Superseded"),
                    ("OBSOLETE", "Obsolete"),
                    ("TERMINATED", "Terminated"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("REVIEW_COMPLETED", "Review Completed"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("UNDER_APPROVAL", "Under Approval"),
                    ("APPROVED", "Approved"),
                    ("APPROVED_AND_EFFECTIVE", "Approved and Effective"),
                    ("APPROVED_PENDING_EFFECTIVE", "Approved Pending Effective"),
                    ("EFFECTIVE", "Effective"),
                    ("SCHEDULED_FOR_OBSOLESCENCE", "Scheduled for Obsolescence"),
                    ("SUPERSEDED", "Superseded"),
                    ("OBSOLETE", "Obsolete"),
                    ("TERMINATED", "Terminated"),
                ],
                max_length=30,
            ),
        ),
    ]
