import { test, expect } from '@playwright/test';

test('create draft document', async ({ page }) => { 
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('author01');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('P@ssword1234');
  await page.getByRole('button', { name: 'Show password' }).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  
  await page.getByRole('link', { name: 'My Tasks' }).click();
  await page.getByRole('button', { name: '📝 Create Document' }).click();
  await page.getByRole('button', { name: 'Click to upload' }).click();
  await page.getByRole('button', { name: 'Click to upload' }).setInputFiles('edms_template.docx');
  await page.getByRole('textbox', { name: 'Document Title *' }).dblclick();
  await page.getByRole('textbox', { name: 'Document Title *' }).fill('Policy_01');
  await page.getByRole('textbox', { name: 'Description *' }).click();
  await page.getByRole('textbox', { name: 'Description *' }).fill('This is the first policy.');
  await page.getByLabel('Document Type *').selectOption('4');
  await page.getByLabel('Document Source *').selectOption('1');
  await page.getByRole('button', { name: 'Create Document', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search documents by title,' }).click();
  await page.getByRole('textbox', { name: 'Search documents by title,' }).fill('Policy_01');
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(5).click();
  await expect(page.locator('.space-y-4').first()).toBeVisible();
  await expect(page.locator('h4')).toContainText('Policy_01');
  await page.getByRole('button', { name: 'workflow' }).click();
  await page.getByRole('button', { name: '📤 Submit for Review Select' }).click();
  await page.getByLabel('Select Reviewer *(Required)').selectOption('119');
  await page.getByRole('textbox', { name: 'Submission Comments(Optional)' }).click();
  await page.getByRole('textbox', { name: 'Submission Comments(Optional)' }).fill('for your review');
  await page.getByRole('button', { name: 'Submit for Review', exact: true }).click();
  await expect(page.getByRole('main')).toContainText('PENDING REVIEW');
  await page.getByRole('button', { name: '👀 Monitor Review Progress' }).click();
  await expect(page.locator('div').filter({ hasText: /^📋 Review Status: Policy_01POL-2025-0001-v01\.00 • Version 1\.0Pending Review$/ }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: '✖️ Clear' }).click();
  await expect(page.locator('.bg-white.rounded-lg.shadow-sm.border.border-gray-200.p-8')).toBeVisible();
  await page.getByRole('button', { name: 'Account Options' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
});

test('review document', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('reviewer01');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('test123');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('P@ssword1234');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'My Tasks' }).click();
  await page.getByRole('textbox', { name: 'Search documents by title,' }).click();
  await page.getByRole('textbox', { name: 'Search documents by title,' }).fill('Policy_01');
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(5).click();
  await page.getByRole('button', { name: 'workflow' }).click();
  await page.getByRole('button', { name: '📋 Start Review Process' }).click();
  await page.getByRole('button', { name: 'Approve Document will be' }).click();
  await page.getByRole('textbox', { name: 'Provide your review comments' }).click();
  await page.getByRole('textbox', { name: 'Provide your review comments' }).fill('good review.');
  await page.getByRole('button', { name: 'Submit Review' }).click();
  await page.getByRole('button', { name: 'Confirm Approval' }).click();
  await expect(page.getByRole('main')).toContainText('REVIEWED');
  await page.getByRole('button', { name: 'Account Options' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
});

test('send for approval', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('author01');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('P@ssword1234');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'My Tasks' }).click();
  await expect(page.getByRole('main')).toContainText('REVIEWED');
  await page.getByRole('button', { name: 'workflow' }).click();
  await page.getByRole('button', { name: '✅ Route for Approval (Author' }).click();
  await page.getByLabel('Select Approver *(Required)').selectOption('120');
  await page.getByRole('textbox', { name: 'Routing Comments(Optional)' }).click();
  await page.getByRole('textbox', { name: 'Routing Comments(Optional)' }).fill('for your approval');
  await page.getByRole('button', { name: 'Route for Approval', exact: true }).click();
  await expect(page.getByRole('main')).toContainText('PENDING APPROVAL');
  await page.getByRole('button', { name: 'Account Options' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
});

test('approve document', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('approver01');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('P@ssword1234');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'My Tasks' }).click();
  await page.getByRole('textbox', { name: 'Search documents by title,' }).click();
  await page.getByRole('textbox', { name: 'Search documents by title,' }).fill('Policy_01');
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(5).click();
  await expect(page.getByRole('main')).toContainText('PENDING APPROVAL');
  await page.getByRole('button', { name: 'workflow' }).click();
  await page.getByRole('button', { name: '✅ Start Approval Process' }).click();
  await page.getByRole('button', { name: 'Approve Document Document' }).click();
  await page.getByRole('textbox', { name: 'Provide your approval' }).click();
  await page.getByRole('textbox', { name: 'Provide your approval' }).fill('Good approved.');
  await page.getByRole('button', { name: 'Submit Approval Decision' }).click();
  await page.getByRole('button', { name: 'Confirm Approval' }).click();
  await page.getByRole('link', { name: 'Document Library' }).click();
  await page.getByRole('textbox', { name: 'Search documents by title,' }).click();
  await page.getByRole('textbox', { name: 'Search documents by title,' }).fill('Policy_01');
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(5).click();
  await expect(page.getByRole('main')).toContainText('EFFECTIVE');
  await page.getByRole('button', { name: 'history' }).click();
  await page.getByRole('button', { name: '✖️ Clear' }).click();
  await expect(page.locator('.bg-white.rounded-lg.shadow-sm.border.border-gray-200.p-8')).toBeVisible();
  await page.getByRole('button', { name: 'Account Options' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
});


