# Generated by Django 4.2.16 on 2026-01-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0003_remove_notificationqueue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentschedule",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="documentschedule",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentschedule",
            name="executed_by",
        ),
        migrations.RemoveField(
            model_name="documentschedule",
            name="notification_users",
        ),
        migrations.RemoveField(
            model_name="notificationqueue",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="notificationqueue",
            name="recipients",
        ),
        migrations.DeleteModel(
            name="SystemHealthCheck",
        ),
        migrations.RemoveField(
            model_name="taskexecution",
            name="scheduled_task",
        ),
        migrations.RemoveField(
            model_name="taskexecution",
            name="triggered_by",
        ),
        migrations.AlterModelOptions(
            name="scheduledtask",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="scheduledtask",
            name="scheduled_t_task_ty_690fc9_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduledtask",
            name="scheduled_t_next_ru_ded61d_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduledtask",
            name="scheduled_t_is_runn_67a0e0_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduledtask",
            name="scheduled_t_frequen_97eafd_idx",
        ),
        migrations.RemoveField(
            model_name="scheduledtask",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="cron_expression",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="failed_runs",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="frequency_type",
            field=models.CharField(default="ONCE", max_length=20),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="interval_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="max_retries",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="retry_delay_seconds",
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="status",
            field=models.CharField(default="ACTIVE", max_length=20),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="successful_runs",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="task_function",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="task_module",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="task_type",
            field=models.CharField(default="CUSTOM", max_length=50),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="timeout_seconds",
            field=models.IntegerField(default=3600),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="total_runs",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="uuid",
            field=models.UUIDField(
                default=None, editable=False, null=True, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="DocumentSchedule",
        ),
        migrations.DeleteModel(
            name="NotificationQueue",
        ),
        migrations.DeleteModel(
            name="TaskExecution",
        ),
    ]
