# Generated by Django 4.2.16 on 2025-11-25 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("audit", "0004_fix_login_audit_user_agent_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="databasechangelog",
            name="action",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="databasechangelog",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="databasechangelog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="databasechangelog",
            name="object_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="databasechangelog",
            name="session_id",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
