# Generated by Django 4.2.7 on 2025-11-21 07:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('ca_type', models.CharField(choices=[('root', 'Root CA'), ('intermediate', 'Intermediate CA'), ('issuing', 'Issuing CA'), ('self_signed', 'Self-Signed')], max_length=20)),
                ('certificate_pem', models.TextField()),
                ('public_key_pem', models.TextField()),
                ('subject', models.CharField(max_length=500)),
                ('issuer', models.CharField(max_length=500)),
                ('serial_number', models.CharField(max_length=100)),
                ('fingerprint_sha256', models.CharField(max_length=64)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Certificate Authority',
                'verbose_name_plural': 'Certificate Authorities',
                'db_table': 'security_certificate_authorities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signature_data', models.TextField()),
                ('algorithm', models.CharField(choices=[('RSA-PSS-SHA256', 'RSA-PSS with SHA-256'), ('RSA-PKCS1-SHA256', 'RSA-PKCS1 with SHA-256'), ('ECDSA-SHA256', 'ECDSA with SHA-256'), ('EdDSA', 'Edwards-curve Digital Signature Algorithm')], max_length=30)),
                ('document_hash', models.CharField(max_length=64)),
                ('signer_certificate', models.TextField(blank=True, null=True)),
                ('signer_role', models.CharField(blank=True, max_length=100, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('pending', 'Pending Verification')], default='pending', max_length=20)),
                ('is_valid', models.BooleanField(blank=True, null=True)),
                ('validation_message', models.TextField(blank=True)),
                ('timestamp_token', models.TextField(blank=True, null=True)),
                ('timestamp_authority', models.CharField(blank=True, max_length=200, null=True)),
                ('signature_purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Digital Signature',
                'verbose_name_plural': 'Digital Signatures',
                'db_table': 'security_digital_signatures',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('key_type', models.CharField(choices=[('master', 'Master Key'), ('document', 'Document Key'), ('backup', 'Backup Key'), ('temp', 'Temporary Key')], max_length=20)),
                ('algorithm', models.CharField(choices=[('AES-256', 'AES 256-bit'), ('Fernet', 'Fernet (AES 128-bit)'), ('RSA-2048', 'RSA 2048-bit'), ('RSA-4096', 'RSA 4096-bit')], max_length=20)),
                ('key_id', models.CharField(max_length=64, unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('key_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Encryption Key',
                'verbose_name_plural': 'Encryption Keys',
                'db_table': 'security_encryption_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('encryption', 'File Encryption'), ('decryption', 'File Decryption'), ('signature_creation', 'Signature Creation'), ('signature_verification', 'Signature Verification'), ('key_generation', 'Key Generation'), ('key_revocation', 'Key Revocation'), ('access_granted', 'Access Granted'), ('access_denied', 'Access Denied'), ('integrity_check', 'Integrity Check'), ('security_violation', 'Security Violation')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.document')),
                ('encryption_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='security.encryptionkey')),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'db_table': 'security_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
