# Generated by Django 4.2.7 on 2025-11-21 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('backup_type', models.CharField(choices=[('FULL', 'Full Backup'), ('INCREMENTAL', 'Incremental Backup'), ('DIFFERENTIAL', 'Differential Backup'), ('DATABASE', 'Database Only'), ('FILES', 'Files Only')], max_length=20)),
                ('frequency', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ON_DEMAND', 'On Demand')], max_length=20)),
                ('schedule_time', models.TimeField(help_text='Time of day to run backup (for daily/weekly/monthly)')),
                ('schedule_days', models.JSONField(blank=True, default=list, help_text='Days of week for weekly backups (0=Monday, 6=Sunday)')),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='Number of days to keep backups')),
                ('max_backups', models.PositiveIntegerField(default=10, help_text='Maximum number of backups to keep')),
                ('storage_path', models.CharField(help_text='Path where backups will be stored', max_length=500)),
                ('compression_enabled', models.BooleanField(default=True, help_text='Enable backup compression')),
                ('encryption_enabled', models.BooleanField(default=True, help_text='Enable backup encryption')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configurations',
                'db_table': 'backup_configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_name', models.CharField(max_length=200)),
                ('backup_type', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=20)),
                ('backup_file_path', models.CharField(blank=True, max_length=500)),
                ('backup_size', models.BigIntegerField(blank=True, help_text='Backup file size in bytes', null=True)),
                ('compression_ratio', models.FloatField(blank=True, help_text='Compression ratio (original/compressed)', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum of backup file', max_length=64)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Backup Job',
                'verbose_name_plural': 'Backup Jobs',
                'db_table': 'backup_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisasterRecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('disaster_type', models.CharField(choices=[('HARDWARE_FAILURE', 'Hardware Failure'), ('SOFTWARE_FAILURE', 'Software Failure'), ('DATA_CORRUPTION', 'Data Corruption'), ('SECURITY_BREACH', 'Security Breach'), ('NATURAL_DISASTER', 'Natural Disaster'), ('POWER_OUTAGE', 'Power Outage'), ('NETWORK_FAILURE', 'Network Failure')], max_length=30)),
                ('recovery_procedures', models.TextField(help_text='Step-by-step recovery procedures')),
                ('estimated_recovery_time', models.DurationField(help_text='Estimated time to complete recovery')),
                ('required_resources', models.JSONField(default=list, help_text='Resources required for recovery')),
                ('responsible_team', models.JSONField(default=list, help_text='Team members responsible for executing plan')),
                ('emergency_contacts', models.JSONField(default=list, help_text='Emergency contact information')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_REVIEW', 'Under Review')], default='DRAFT', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_results', models.TextField(blank=True)),
                ('next_test_due', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disaster Recovery Plan',
                'verbose_name_plural': 'Disaster Recovery Plans',
                'db_table': 'disaster_recovery_plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('check_name', models.CharField(max_length=200)),
                ('check_type', models.CharField(choices=[('DATABASE', 'Database Health'), ('STORAGE', 'Storage Health'), ('APPLICATION', 'Application Health'), ('NETWORK', 'Network Connectivity'), ('SERVICES', 'External Services'), ('BACKUP_SYSTEM', 'Backup System'), ('SECURITY', 'Security Status')], max_length=20)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed check results')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Performance and health metrics')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Health Check',
                'verbose_name_plural': 'Health Checks',
                'db_table': 'health_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('restore_type', models.CharField(choices=[('FULL_RESTORE', 'Full System Restore'), ('DATABASE_RESTORE', 'Database Restore'), ('FILES_RESTORE', 'Files Restore'), ('SELECTIVE_RESTORE', 'Selective Restore')], max_length=20)),
                ('target_location', models.CharField(help_text='Target location for restore', max_length=500)),
                ('restore_options', models.JSONField(blank=True, default=dict, help_text='Restore-specific options')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('restored_items_count', models.PositiveIntegerField(default=0)),
                ('failed_items_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('restore_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Restore Job',
                'verbose_name_plural': 'Restore Jobs',
                'db_table': 'restore_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('metric_name', models.CharField(max_length=200)),
                ('metric_type', models.CharField(choices=[('CPU_USAGE', 'CPU Usage'), ('MEMORY_USAGE', 'Memory Usage'), ('DISK_USAGE', 'Disk Usage'), ('NETWORK_IO', 'Network I/O'), ('DATABASE_PERFORMANCE', 'Database Performance'), ('APPLICATION_PERFORMANCE', 'Application Performance'), ('USER_ACTIVITY', 'User Activity'), ('DOCUMENT_ACTIVITY', 'Document Activity')], max_length=30)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('warning_threshold', models.FloatField(blank=True, null=True)),
                ('critical_threshold', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metric metadata')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'db_table': 'system_metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['metric_type', 'recorded_at'], name='system_metr_metric__fcce09_idx'), models.Index(fields=['metric_name', 'recorded_at'], name='system_metr_metric__fa0c2d_idx'), models.Index(fields=['status'], name='system_metr_status_1e6815_idx')],
            },
        ),
    ]
