# Generated by Django 4.2.7 on 2025-11-21 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorejob',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_restores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restorejob',
            name='backup_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restore_jobs', to='backup.backupjob'),
        ),
        migrations.AddField(
            model_name='restorejob',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_restores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='healthcheck',
            index=models.Index(fields=['check_type', 'status'], name='health_chec_check_t_ab5356_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcheck',
            index=models.Index(fields=['status', 'checked_at'], name='health_chec_status_efc4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcheck',
            index=models.Index(fields=['check_name'], name='health_chec_check_n_aa52c0_idx'),
        ),
        migrations.AddField(
            model_name='disasterrecoveryplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_dr_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disasterrecoveryplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dr_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to='backup.backupconfiguration'),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backupconfiguration',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_backup_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='restorejob',
            index=models.Index(fields=['status', 'created_at'], name='restore_job_status_f5b3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='restorejob',
            index=models.Index(fields=['restore_type'], name='restore_job_restore_4fd9f4_idx'),
        ),
        migrations.AddIndex(
            model_name='restorejob',
            index=models.Index(fields=['requested_by'], name='restore_job_request_4b97bd_idx'),
        ),
        migrations.AddIndex(
            model_name='disasterrecoveryplan',
            index=models.Index(fields=['disaster_type'], name='disaster_re_disaste_715fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='disasterrecoveryplan',
            index=models.Index(fields=['status'], name='disaster_re_status_b3060a_idx'),
        ),
        migrations.AddIndex(
            model_name='disasterrecoveryplan',
            index=models.Index(fields=['next_test_due'], name='disaster_re_next_te_f6ef26_idx'),
        ),
        migrations.AddIndex(
            model_name='backupjob',
            index=models.Index(fields=['status', 'created_at'], name='backup_jobs_status_2aa3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='backupjob',
            index=models.Index(fields=['configuration', 'created_at'], name='backup_jobs_configu_f2480a_idx'),
        ),
        migrations.AddIndex(
            model_name='backupjob',
            index=models.Index(fields=['backup_type'], name='backup_jobs_backup__778838_idx'),
        ),
        migrations.AddIndex(
            model_name='backupconfiguration',
            index=models.Index(fields=['backup_type'], name='backup_conf_backup__7b785d_idx'),
        ),
        migrations.AddIndex(
            model_name='backupconfiguration',
            index=models.Index(fields=['frequency'], name='backup_conf_frequen_8df4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='backupconfiguration',
            index=models.Index(fields=['status', 'is_enabled'], name='backup_conf_status_bf475f_idx'),
        ),
    ]
