# Generated by Django 4.2.7 on 2025-11-21 07:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('schedule_type', models.CharField(choices=[('EFFECTIVE_DATE', 'Make Effective on Date'), ('REVIEW_DUE', 'Review Due Reminder'), ('OBSOLETE_DATE', 'Make Obsolete on Date'), ('ARCHIVE_DATE', 'Archive on Date'), ('REMINDER', 'Send Reminder'), ('WORKFLOW_TIMEOUT', 'Workflow Timeout')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Document Schedule',
                'verbose_name_plural': 'Document Schedules',
                'db_table': 'document_schedules',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('TASK_REMINDER', 'Task Reminder'), ('DOCUMENT_DUE', 'Document Due Notification'), ('WORKFLOW_OVERDUE', 'Workflow Overdue'), ('SYSTEM_ALERT', 'System Alert'), ('HEALTH_CHECK', 'Health Check Alert'), ('BACKUP_STATUS', 'Backup Status'), ('MAINTENANCE', 'Maintenance Notification')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('recipient_emails', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_data', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('delivery_channels', models.JSONField(blank=True, default=list)),
                ('delivery_attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Notification Queue',
                'verbose_name_plural': 'Notification Queue',
                'db_table': 'notification_queue',
                'ordering': ['scheduled_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('DOCUMENT_EFFECTIVE', 'Make Documents Effective'), ('DOCUMENT_OBSOLETE', 'Process Document Obsolescence'), ('REVIEW_REMINDER', 'Send Review Reminders'), ('APPROVAL_REMINDER', 'Send Approval Reminders'), ('OVERDUE_NOTIFICATION', 'Send Overdue Notifications'), ('HEALTH_CHECK', 'System Health Check'), ('DATABASE_BACKUP', 'Database Backup'), ('FILE_CLEANUP', 'Cleanup Temporary Files'), ('AUDIT_CLEANUP', 'Cleanup Old Audit Logs'), ('WORKFLOW_TIMEOUT', 'Handle Workflow Timeouts'), ('DEPENDENCY_CHECK', 'Check Document Dependencies'), ('CUSTOM', 'Custom Task')], max_length=30)),
                ('task_module', models.CharField(max_length=200)),
                ('task_function', models.CharField(max_length=100)),
                ('task_args', models.JSONField(blank=True, default=list)),
                ('task_kwargs', models.JSONField(blank=True, default=dict)),
                ('frequency_type', models.CharField(choices=[('ONCE', 'Run Once'), ('MINUTELY', 'Every Minute'), ('HOURLY', 'Every Hour'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CRON', 'Custom Cron Expression')], default='DAILY', max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text='Cron expression for custom scheduling', max_length=100)),
                ('interval_value', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=3600)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('retry_delay_seconds', models.PositiveIntegerField(default=300)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ERROR', 'Error')], default='ACTIVE', max_length=20)),
                ('is_running', models.BooleanField(default=False)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('successful_runs', models.PositiveIntegerField(default=0)),
                ('failed_runs', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Scheduled Task',
                'verbose_name_plural': 'Scheduled Tasks',
                'db_table': 'scheduled_tasks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('check_type', models.CharField(choices=[('DATABASE', 'Database Connectivity'), ('REDIS', 'Redis Connectivity'), ('CELERY', 'Celery Worker Status'), ('DISK_SPACE', 'Disk Space Usage'), ('MEMORY', 'Memory Usage'), ('CPU', 'CPU Usage'), ('DOCUMENT_INTEGRITY', 'Document File Integrity'), ('WORKFLOW_HEALTH', 'Workflow Engine Health'), ('BACKUP_STATUS', 'Backup System Status'), ('AUDIT_TRAIL', 'Audit Trail Integrity')], max_length=30)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('threshold_warning', models.FloatField(blank=True, null=True)),
                ('threshold_critical', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'System Health Check',
                'verbose_name_plural': 'System Health Checks',
                'db_table': 'system_health_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('CANCELLED', 'Cancelled')], default='RUNNING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('worker_hostname', models.CharField(blank=True, max_length=255)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('output_log', models.TextField(blank=True)),
                ('execution_time', models.DurationField(blank=True, null=True)),
                ('memory_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scheduled_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scheduler.scheduledtask')),
            ],
            options={
                'verbose_name': 'Task Execution',
                'verbose_name_plural': 'Task Executions',
                'db_table': 'task_executions',
                'ordering': ['-started_at'],
            },
        ),
    ]
