# Generated by Django 4.2.7 on 2025-11-21 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggered_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='systemhealthcheck',
            index=models.Index(fields=['check_type', 'checked_at'], name='system_heal_check_t_b8876f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthcheck',
            index=models.Index(fields=['status', 'checked_at'], name='system_heal_status_526ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthcheck',
            index=models.Index(fields=['checked_at'], name='system_heal_checked_218935_idx'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationqueue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationqueue',
            name='recipients',
            field=models.ManyToManyField(related_name='queued_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentschedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentschedule',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentschedule',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_document_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentschedule',
            name='notification_users',
            field=models.ManyToManyField(blank=True, related_name='document_schedule_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['scheduled_task', 'started_at'], name='task_execut_schedul_efabfc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['status', 'started_at'], name='task_execut_status_fc1106_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['celery_task_id'], name='task_execut_celery__714fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['task_type', 'status'], name='scheduled_t_task_ty_690fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['next_run', 'status'], name='scheduled_t_next_ru_ded61d_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['is_running'], name='scheduled_t_is_runn_67a0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['frequency_type'], name='scheduled_t_frequen_97eafd_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['scheduled_at', 'status'], name='notificatio_schedul_b46d89_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['status', 'priority'], name='notificatio_status_a3b62f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_2281fa_idx'),
        ),
        migrations.AddIndex(
            model_name='documentschedule',
            index=models.Index(fields=['document', 'schedule_type'], name='document_sc_documen_f1735c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentschedule',
            index=models.Index(fields=['scheduled_date', 'status'], name='document_sc_schedul_3c20d2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentschedule',
            index=models.Index(fields=['status'], name='document_sc_status_0ed994_idx'),
        ),
    ]
