# Generated by Django 4.2.7 on 2025-11-21 07:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('output_format', models.CharField(max_length=20)),
                ('context_data', models.JSONField(default=dict, help_text='Data used for placeholder replacement')),
                ('generation_options', models.JSONField(blank=True, default=dict, help_text='Additional options for document generation')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('output_file_path', models.CharField(blank=True, max_length=500)),
                ('output_filename', models.CharField(blank=True, max_length=200)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_checksum', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Generation',
                'verbose_name_plural': 'Document Generations',
                'db_table': 'document_generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('DOCX', 'Word Document (.docx)'), ('PDF', 'PDF Document (.pdf)'), ('HTML', 'HTML Document (.html)'), ('TEXT', 'Text Document (.txt)'), ('CUSTOM', 'Custom Format')], max_length=20)),
                ('file_path', models.CharField(help_text='Path to template file', max_length=500)),
                ('output_filename_pattern', models.CharField(default='{DOC_NUMBER}_{DOC_TITLE}', help_text='Pattern for output filename using placeholders', max_length=200)),
                ('processing_rules', models.JSONField(blank=True, default=dict, help_text='Processing rules and configurations')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this type')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'db_table': 'document_templates',
                'ordering': ['name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='PlaceholderCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cache_key', models.CharField(max_length=255)),
                ('cached_value', models.TextField()),
                ('context_hash', models.CharField(help_text='Hash of the context data used to generate this value', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Placeholder Cache',
                'verbose_name_plural': 'Placeholder Cache',
                'db_table': 'placeholder_cache',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceholderDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Placeholder name (e.g., DOC_NUMBER, AUTHOR_NAME)', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Placeholder name must be uppercase with underscores only', regex='^[A-Z][A-Z0-9_]*$')])),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('placeholder_type', models.CharField(choices=[('DOCUMENT', 'Document Metadata'), ('USER', 'User Information'), ('WORKFLOW', 'Workflow Data'), ('SYSTEM', 'System Information'), ('DATE', 'Date/Time'), ('CUSTOM', 'Custom Field'), ('CONDITIONAL', 'Conditional Logic')], max_length=20)),
                ('data_source', models.CharField(choices=[('DOCUMENT_MODEL', 'Document Model Field'), ('USER_MODEL', 'User Model Field'), ('WORKFLOW_MODEL', 'Workflow Model Field'), ('SYSTEM_CONFIG', 'System Configuration'), ('COMPUTED', 'Computed Value'), ('JSONB_FIELD', 'JSONB Metadata Field')], max_length=30)),
                ('source_field', models.CharField(help_text='Model field name or configuration key', max_length=100)),
                ('format_string', models.CharField(blank=True, help_text="Python format string (e.g., '{:.2f}' for decimals)", max_length=100)),
                ('date_format', models.CharField(blank=True, default='%Y-%m-%d', help_text='Date format string (e.g., %Y-%m-%d)', max_length=50)),
                ('default_value', models.TextField(blank=True, help_text='Default value if source data is not available')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules for placeholder values')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_permission', models.CharField(blank=True, help_text='Permission level required to access this placeholder', max_length=50)),
                ('cache_duration', models.PositiveIntegerField(default=0, help_text='Cache duration in seconds (0 = no cache)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placeholder Definition',
                'verbose_name_plural': 'Placeholder Definitions',
                'db_table': 'placeholder_definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplatePlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this placeholder is required for this template')),
                ('default_value', models.TextField(blank=True, help_text='Template-specific default value')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Template-specific validation rules')),
                ('order', models.PositiveIntegerField(default=0)),
                ('format_override', models.CharField(blank=True, help_text='Override format string for this template', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_usages', to='placeholders.placeholderdefinition')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_placeholders', to='placeholders.documenttemplate')),
            ],
            options={
                'verbose_name': 'Template Placeholder',
                'verbose_name_plural': 'Template Placeholders',
                'db_table': 'template_placeholders',
                'ordering': ['order', 'placeholder__name'],
            },
        ),
    ]
