# Generated by Django 4.2.16 on 2025-11-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0006_alter_databasechangelog_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="databasechangelog",
            name="integrity_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
