# Generated by Django 4.2.16 on 2026-01-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_add_periodic_review_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='review_period_months',
            field=models.PositiveIntegerField(
                null=True,
                blank=True,
                default=None,
                help_text='Number of months between periodic reviews (null if no periodic review required)'
            ),
        ),
    ]
