# Generated by Django 4.2.16 on 2026-02-06 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_add_sensitivity_labels"),
        ("documents", "0004_make_review_period_nullable"),
    ]

    operations = []
