# Generated by Django 4.2.7 on 2025-11-21 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentdependency',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentdependency',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentdependency',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='documents.documentcomment'),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='document_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentsource'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='documents.document'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'version_major', 'version_minor'], name='document_ve_documen_8a0a55_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['created_at'], name='document_ve_created_c8d81d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['created_by'], name='document_ve_created_11bca2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_major', 'version_minor')},
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['code'], name='document_ty_code_45b0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['is_active'], name='document_ty_is_acti_8fb3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdependency',
            index=models.Index(fields=['document', 'dependency_type'], name='document_de_documen_1acfbd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdependency',
            index=models.Index(fields=['depends_on', 'is_critical'], name='document_de_depends_c74bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdependency',
            index=models.Index(fields=['is_active'], name='document_de_is_acti_388fed_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentdependency',
            constraint=models.CheckConstraint(check=models.Q(('document', models.F('depends_on')), _negated=True), name='no_self_dependency'),
        ),
        migrations.AlterUniqueTogether(
            name='documentdependency',
            unique_together={('document', 'depends_on', 'dependency_type')},
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['document', 'created_at'], name='document_co_documen_199324_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['author', 'created_at'], name='document_co_author__e0aaee_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['comment_type', 'is_resolved'], name='document_co_comment_afc002_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['requires_response', 'is_resolved'], name='document_co_require_00cce9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['document', 'attachment_type'], name='document_at_documen_012ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['file_checksum'], name='document_at_file_ch_45898f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['uploaded_at'], name='document_at_uploade_0f3fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['is_active'], name='document_at_is_acti_0fc9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['document', 'access_timestamp'], name='document_ac_documen_c1c5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['user', 'access_timestamp'], name='document_ac_user_id_03b21d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['access_type', 'access_timestamp'], name='document_ac_access__d44827_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['ip_address', 'access_timestamp'], name='document_ac_ip_addr_3f0f17_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['success'], name='document_ac_success_0da76c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_number'], name='documents_documen_19bab8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'effective_date'], name='documents_status_65a9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['author', 'status'], name='documents_author__5834d2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'status'], name='documents_documen_f2a694_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_created_3c6eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['effective_date'], name='documents_effecti_70d0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['review_due_date'], name='documents_review__367769_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_checksum'], name='documents_file_ch_9b5751_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_active', 'status'], name='documents_is_acti_e8c494_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('version_major__gte', 1)), name='version_major_positive'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('version_minor__gte', 0)), name='version_minor_non_negative'),
        ),
    ]
