# Generated by Django 4.2.16 on 2025-11-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_alter_document_effective_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("REVIEW_COMPLETED", "Review Completed"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("UNDER_APPROVAL", "Under Approval"),
                    ("APPROVED", "Approved"),
                    ("APPROVED_AND_EFFECTIVE", "Approved and Effective"),
                    ("APPROVED_PENDING_EFFECTIVE", "Approved Pending Effective"),
                    ("EFFECTIVE", "Effective"),
                    ("SUPERSEDED", "Superseded"),
                    ("OBSOLETE", "Obsolete"),
                    ("TERMINATED", "Terminated"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("REVIEW_COMPLETED", "Review Completed"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("UNDER_APPROVAL", "Under Approval"),
                    ("APPROVED", "Approved"),
                    ("APPROVED_AND_EFFECTIVE", "Approved and Effective"),
                    ("APPROVED_PENDING_EFFECTIVE", "Approved Pending Effective"),
                    ("EFFECTIVE", "Effective"),
                    ("SUPERSEDED", "Superseded"),
                    ("OBSOLETE", "Obsolete"),
                    ("TERMINATED", "Terminated"),
                ],
                max_length=30,
            ),
        ),
    ]
