# Generated by Django 4.2.7 on 2025-11-21 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='security.digitalsignature'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encryptionkey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encryptionkey',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='documents.document'),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='parent_ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_cas', to='security.certificateauthority'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='security_ev_event_t_efa0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['severity', 'is_resolved'], name='security_ev_severit_198ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', 'timestamp'], name='security_ev_user_id_6a5f21_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['document', 'event_type'], name='security_ev_documen_aa66d0_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptionkey',
            index=models.Index(fields=['key_type', 'is_active'], name='security_en_key_typ_d28ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptionkey',
            index=models.Index(fields=['key_id'], name='security_en_key_id_2bd5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptionkey',
            index=models.Index(fields=['fingerprint'], name='security_en_fingerp_ce0d45_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalsignature',
            index=models.Index(fields=['document', 'signer'], name='security_di_documen_229af2_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalsignature',
            index=models.Index(fields=['status', 'is_valid'], name='security_di_status_15fe8b_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalsignature',
            index=models.Index(fields=['signed_at'], name='security_di_signed__43d927_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalsignature',
            index=models.Index(fields=['document_hash'], name='security_di_documen_972325_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateauthority',
            index=models.Index(fields=['ca_type', 'is_valid'], name='security_ce_ca_type_fec40b_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateauthority',
            index=models.Index(fields=['fingerprint_sha256'], name='security_ce_fingerp_bebee9_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateauthority',
            index=models.Index(fields=['serial_number'], name='security_ce_serial__09eb13_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateauthority',
            index=models.Index(fields=['valid_until'], name='security_ce_valid_u_9c1e91_idx'),
        ),
    ]
