# Generated by Django 4.2.16 on 2025-11-27 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_alter_document_effective_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("security", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFSigningCertificate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Certificate friendly name", max_length=200
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("SELF_SIGNED", "Self-Signed"),
                            ("CA_ISSUED", "Certificate Authority Issued"),
                            ("DEVELOPMENT", "Development Only"),
                        ],
                        default="SELF_SIGNED",
                        max_length=20,
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(help_text="PEM encoded certificate"),
                ),
                (
                    "private_key_pem",
                    models.TextField(help_text="PEM encoded private key"),
                ),
                (
                    "public_key_pem",
                    models.TextField(help_text="PEM encoded public key"),
                ),
                (
                    "subject_cn",
                    models.CharField(
                        help_text="Certificate Common Name", max_length=200
                    ),
                ),
                (
                    "issuer_name",
                    models.CharField(help_text="Certificate Issuer", max_length=200),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default certificate for PDF signing"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF Signing Certificate",
                "verbose_name_plural": "PDF Signing Certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PDFGenerationLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("DOCX_TO_PDF", "DOCX to PDF"),
                            ("FILE_TO_PDF", "File to PDF"),
                            ("PDF_PASSTHROUGH", "PDF Passthrough"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("TIMEOUT", "Timeout"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Processing time in milliseconds"
                    ),
                ),
                (
                    "input_file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="Input file size in bytes"
                    ),
                ),
                (
                    "output_file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="Generated PDF size in bytes"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("signature_applied", models.BooleanField(default=False)),
                ("metadata_embedded", models.BooleanField(default=False)),
                ("watermark_applied", models.BooleanField(default=False)),
                ("qr_code_added", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="security.pdfsigningcertificate",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF Generation Log",
                "verbose_name_plural": "PDF Generation Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
