# Generated by Django 4.2.7 on 2025-11-22 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentState',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'workflow_document_states',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('workflow_data', models.JSONField(blank=True, default=dict)),
                ('current_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_document_workflows', to=settings.AUTH_USER_MODEL)),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='workflows.documentstate')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='documents.document')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_document_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_workflows',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('transition_data', models.JSONField(blank=True, default=dict)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_from', to='workflows.documentstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_to', to='workflows.documentstate')),
                ('transitioned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_transitions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.documentworkflow')),
            ],
            options={
                'db_table': 'document_transitions',
                'ordering': ['-transitioned_at'],
            },
        ),
    ]
