# Generated by Django 4.2.7 on 2025-11-21 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicustomization',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uicustomization',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='Specific users this customization applies to', related_name='ui_customizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_notification_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featuretoggle',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_feature_toggles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featuretoggle',
            name='target_users',
            field=models.ManyToManyField(blank=True, help_text='Users who have access to this feature', related_name='feature_toggles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationhistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationhistory',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='settings.systemconfiguration'),
        ),
        migrations.AddIndex(
            model_name='uicustomization',
            index=models.Index(fields=['customization_type', 'status'], name='ui_customiz_customi_6e1f69_idx'),
        ),
        migrations.AddIndex(
            model_name='uicustomization',
            index=models.Index(fields=['is_default'], name='ui_customiz_is_defa_496245_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfiguration',
            index=models.Index(fields=['category'], name='system_conf_categor_a4e81d_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfiguration',
            index=models.Index(fields=['key'], name='system_conf_key_35f9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfiguration',
            index=models.Index(fields=['setting_type'], name='system_conf_setting_053688_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['template_type', 'event_type'], name='notificatio_templat_234e62_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_active', 'is_default'], name='notificatio_is_acti_61a7bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('template_type', 'event_type', 'is_default'), name='unique_default_template'),
        ),
        migrations.AddIndex(
            model_name='featuretoggle',
            index=models.Index(fields=['key'], name='feature_tog_key_d0a9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='featuretoggle',
            index=models.Index(fields=['toggle_type', 'is_enabled'], name='feature_tog_toggle__4a559a_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationhistory',
            index=models.Index(fields=['configuration', 'changed_at'], name='configurati_configu_848601_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationhistory',
            index=models.Index(fields=['changed_by', 'changed_at'], name='configurati_changed_2b1006_idx'),
        ),
    ]
