# Generated by Django 4.2.16 on 2025-11-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0005_databasechangelog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databasechangelog",
            name="action",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="databasechangelog",
            name="session_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
